site_name: BiblioTech
site_url: https://documentation-9908be.gitlab.io/
theme:
  name: material
  language: fr
  icon:
    logo: fontawesome/solid/robot
  favicon: assets/favicon.svg
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Passer en thème clair
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Passer en thème sombre
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Passer à la préférence système
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.path
    - navigation.indexes
    - search.suggest
    - navigation.footer
    - content.action.edit
    - content.action.view
    - content.code.copy
    - content.code.annotate
nav:
  - Accueil: index.md
  - Électronique:
    - electronique/index.md
  - Informatique:
    - informatique/index.md
    - Simulation avec PyBullet: informatique/simulation.md
    - Fichiers URDF: informatique/URDF.md
    - Traitement Images: informatique/camera.md
    - Raspberry Pi: informatique/raspberry.md
  - Mécanique:
    - mecanique/index.md
    - Projet & Tech: mecanique/projet-esperluette-tech.md
    - Introduction à la mécanique: mecanique/introduction-mecanique.md
    - SolidWorks: mecanique/solidworks.md
    - Todo: mecanique/todo.md
  - Lore:
    - lore/index.md
plugins:
  - search
  - minify:
      minify_html: true
extra:
  social:
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/projet_tech_42/
      name: Instagram
    - icon: fontawesome/solid/paper-plane
      link: mailto:projet-tech@fatse.fr
      name: Mail
    - icon: fontawesome/brands/github
      link: https://github.com/Projet-et-Tech/
      name: GitHub
copyright: Copyright &copy; 2025 Projet & Tech
markdown_extensions:
  - abbr
  - admonition
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - footnotes
  - toc:
      permalink: true
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - https://tikzjax.com/v1/tikzjax.js
extra_css:
  - https://tikzjax.com/v1/fonts.css
